# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael Sullivan
email: michael@sullivan.work
description: > # this means to ignore newlines until "baseurl:"
  I believe digital tools should make life easier. The interface of these tools should allow a  person to do what they need with as little friction as possible.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mmsullivan
github_username:  mmsullivan

# Build settings
markdown: kramdown
